apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: general-strapi-database-secret
  namespace: standalone
spec:
  encryptedData:
    DATABASE_PASSWORD: AgCr8H5JcSO1lZxrokMjX6Y+gw7eKjQJ//sd+Tzu3mRQxLkxGfEZpSenYG+9R9LRAWz93yiWXWH6ehv0BaX5zAHg5+9sZWjP4gU9BMEZ6uBQgWz4xKBgwgftXjOG5bHdrHBA+9xY93hEZoEz3HGrch7SymhAMM0WIv+luuPWDOHJqK/t4y3R8NhnoAMnz/hgTnz5oC/B1pxzyw1lDhG35cQG9HphY0HSPaIOHE3h+9Mmfm8FJWA1xr4rthT5T8p0BMbWbmfEGwfWNXuQCE3uGneIUm8t41OhZi1ywEbUeISJ77jlgDmmwKhZUxFnx6NuU51Wy4QldCwS6x/Wckyn2PVv/OwZmmhRhoFIv28MmCkztaz7V9mSsUAZw1w3iZ2273e9iLKZqeGzNJ5W9zQRFYCmkQMKmmxkLJodWsdjUm/qV7JMIONG3Ol/Yzzch3QvxI33WP8dwUVYnRnkzlCKHL00kRZmRL01ToabYCbW7MidCUvl4s7d4hw4ZyH/oktscdcnXLQ8Axp0ArvHFxNCxlBA2sSPVhQwYl2VDfK8WtD7dpIfjoBGceFzose3bKj3uaUPIbO4kRVIjn6ZIZN8T8XyZQuUcGZU8u+OIskHjvpi+w6UxjYRUbcNgp04oFPreo2Jq9CxBJ0d8otiBvCpD/qkMgWJjLz9R71dzNLExEV9on4LtLXxiKX3vnFweanu1o0S1UK5YcVAcVLu9dWZTRyQuM7z9GQGfS6oLECdjV8kJSnYp91B4O0KXtN9QB53WW7gE7Q8Lf0hqCH1NcujIOl9+Aio7Xpg
    POSTGRES_PASSWORD: AgBW1zXQ4P5CuAjIRP8qIW/DJ2i/7UjbUVSrdkXeDOVtxt0F4OzJ3wmblNHoO94j5wqSz3oaGNHndtn9ygxnWSO0dk1QsnmxyY6Xsr50E1YADMPHZJko1HIGwk6mBcC4a51ZtdIrF+PaW2i2+IGbWXmzQTpKxEk0isEx/exaV4dwisDu3AKQXFZOWWnrFJj4QGX8lyX/we7SLpcNuH1ZscupxuCViBT6s1lEs43qaNFAc3S3bjucLqzSd7q92v8g/N9BhzeKC1NMxWY4h8Jc/0YolDgUPeFX2XTKQV6PVy1DkcTYXnM/e2rTowooF06fx0GftQAeFVu77hN4E6D2ez0WlfJlVT5JcHu/T+Mf9OtYusHB+DiDx1BwDQGNnaz9PGUSZqUOMVW6caDS8ohe5Y6aRJj09oo1wVvWI3HAe4BpzZOTlsvS4Z5xE4bgmTYIocyamVBdtHXfrV/R1beV9Ft4LW3MGobz1M+SGSqFTAcHtkyY1olBzW3cP+z1fHD8zS7EmoZ5YCHywKd7XG6xEaNTsZ0B8v8XKOCd+yu4g6J/wpMoFCcJ7YWjZjaTalnK2mSSOqCyvzHPqKW/PfGzWUR1epLFImdWx8WqrqzT1awvl6ZxAHT62edambd1k1BWOxLJIXpg3SbafyVpCOvkMkpNPld2G6PHHBU8hvtYN5khm6DElcayGH16VeoWsZgSyf0Aw8zp72Hx3Ys+5KoTqmOG2QFdyK30gUQn8Q5jxj0v51QIfPvOiH54EVCJ0yzV2fv4rA3t6ZUwV3fMkTk5L9NHBeG5Qu9k
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: general-strapi-database-secret
      namespace: standalone

