apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: general-strapi-database-secret
  namespace: standalone
spec:
  encryptedData:
    DATABASE_PASSWORD: AgA0jIj/iLT/aEJsGmc7NDLLgVBCxttpoj+t0aFLc5MWidf4fCtjqqL/Rsx/LRdpfW/apCdCX3LNSZ3GyJzjIX+5A5bc9hHptZC/nR9BF/4Oe8EmtiJ/oIK0Jepqh7QQFP+vqnp7/tDLrGcRZz5IODKZgdRMIyKxV6FCneJzA/gBo3y4OX3oV/M77L2SBQS7wQTsXV3QM+Y66rlCSxW3dLUwRbgczGmrtS56A45uoCj2MXpOD1BhNLZhuHCkG0EIVUcd4Y3TPZGKIlIjrIK4OAO6rvvrlzohbjhO2Drp7qFEp/fOnegO4tAD67/18np9EXxNPWBSPB4YXo3If2JinTNzdpbdNAiLSDvJ2yHDKkPnUn/s2fBxhOFKp7BnaEVVxrS0IcT0SMmOft1qCYkJPfr2QXw8YT1bcxmt2faUPU+K0IUWvavzDnmQih2BsiuD0SGsreGcKlyzq9vjeOTHFSg4oC+lf2a+ZolcNamA5MQNCuKli7NCWsRCKDXrr1tGIKu6emk/0SylWjH1idfZ+etgADO/wNwojC4TrizMaiF/ovohaCMsY7O6GBwoV2lYER3dgViTa+0xHPYL6UY0f1SqL/675s40C8WSaH0BQGO0zTKL17hd5q6QfdI8994cNAciRlKHZw4ckupsioI0peGGvO1SLY5xAtU4nH/GiroJYSKg2L8jFhnjEyNs+nLI5g+uxJTsEgO9wNzE4Ye5wmxdHZv/AalUkHVaURgqkQfUuaXCebKtOw==
    POSTGRES_PASSWORD: AgCpug4BKXJ+kPoIdaKgZnhx6fl32x6T7JoDfiZiEJzjry+FInK2dHGNqD//+1Z8fEggzjf+SsxPPICwfay3qInRGWv+g/r0OIH2oacihbe6ChykoXSG/jUkuSvwAyvm75B6q0Lm+M2C0zO8eAHTjDNFPgmwmPOhGHG8oxq6RQ+/sqdONF1wmfoXziicyiBhNo90WIGScm+vkF/tFsFTIePvl2a+v1L0tWI1rxECAXCZZH3bAuRd1RH8sJutW+hXxRFyGwrxYpvieeeOAZsZ9b6tOlVF0N/IiikyyvYWdCcaGFCNGr76XSAjZIKw//4Z3eOEbBHETkox9oToeKTh/Fp3fdMDViyT6aarTjXz+3rUCpzvjpBw/0D6ZZpuExwZmJYBjmANb8Ty6HDYXFjEZlbvMfHIj0bAjeczBFzsK2drbb6ecNyvPVN6ZKVkav85XL6zmTODNaj1oBwuUOoyqLZtmIt0cFlJ3+K/f8komh5EHE7rcKbqh1JjrhIIwbgZbS0t/4GHwK885wsP2CdOM71wHDE9EaXKI39fLQNsfee3HsCLPrqGdMAkrNWuHSZ94fgXJ+PItIMddhu9LI8wtUQwWRjNMOoqenk1BSrftwDBBHQJkNvmAEA/+0gB61TXq+VCSEIbA+Z17Fl8DJAAAHG73kDI7LAA9bvEp3WtbAJubSHxY0QUrGXjA4CxD7znTCeCkkgANu/NU2lYUbQTnaxF4oUKBoCAtGxZYjkJQVqYNtLLTSVRdQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: general-strapi-database-secret
      namespace: standalone

