apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: general-strapi-database-secret
  namespace: standalone
spec:
  encryptedData:
    DATABASE_PASSWORD: AgA1wEzOXGoNGSqtY3FV3Pdy9xTCfrXVByMoFPE/9ycXVsY8m582sktqcdfNsrDEXhAY8z+19ISwtlRpdc+uZhM+Ee8jbSv32AFaarI+dUraPpyv47rvJQN4EmUC8/SM6pk/gZrPi2/lHuc1gPdZK+SebKkK9PdxMadn3YpJpU++O+wjPu86We85SHG5UFH7VJ4ad2UvhGdTqfTtV+uRxWi3/4adi/gGPlX29uNA4F50003OCoGr5XaUhn9LmiZjV+3VXzuEOopJxCpmBOB2LLezVJFxpu2ohLeK0XFHvKlS2JwY6bTJeCYF7bVmMkCLMWY65JMbFefpzndvn16iRo765DTCyIWLLqlp87FVTDufl58AOfbZFv9POeP96S14RukLDyoVAiN698+Qpojwy/UEcaWbHIuI0c8v3UfLCVuZQLU+gKZef+7lhZemn0Tc6tCCRapFLT496a+bjv+WtEtUcwhJLScdzawo+A+wq7ZuIRnSS0g9qDCgPQ7CQTzfyimLSz4ZF5Vmo1XNv0J5rtT+GrXvj9a0y0rTIoxzlzls6he2sZuHdftMiKjUzR1djZqnCmXO23X0EN0hjLeeIOqPa4zOy7ffYkGQONIPy4tHWQP5fSbPj2YHdR8SonaO1oYzVvnl3HFyPAl1kMNAYlM64btVcg1n5aYref89w2sxFCYIyleuuiR0cjtEfj0wE4WwPJKp+hdoggzZ5xH67X/qEOS8IEXC2sYroqRqQL7kKLFV/pb8f8r0cl9yNbeykSGvdsx7fMWBNmqp+g==
    POSTGRES_PASSWORD: AgCKxyAyBtF/1x8JcHa8oDo2vTqY/28pXxEqVgE+0B0R5cSLi+19OFiHIXd1BwhlziKuRM+all93j0gmDFCyKfBxPJ+/y7i9JwywsXn7AaIBjkazs9tK8gcKNX3tkKPK/EOEg5xiS8lxdKCOqSslC/VYhBHST0pKp42Ee4uOedCJJ9hXJBqdXpdveHe/sfU1KbqKdYT5CkR2fo1NJPdyD5GGDTQhowck70OSali8vc/TECY61fyY4F6Fw1MemZ/hLNhMU4WoX0WbuoNO58CAWiMYMZbmngUBvdybneksZvBjMYc7i2REI/k0lVd1bZAn3NqEnTcTSLTdaoJNS9lNyO+Gt5v2WfjVSH/jM0WvBQxg61ZRFGdFB5nrVfg1I4vFVCH0MVYTr/y1J05Ajq9gvziagp2SG90STSCgvAAvAhezlcGlDEeTF1QvnWbEgDpaxzyLcV8BlNymTcFqLngfc3sPqMFik/Mhh495EKwqhuCl//WSCbWCI2rNyhlv+A+/7JGdBW8UsvT7Xk6EvL9/gKqPOBul0Wrq+zaN4VjthARM4DvnJ/jtDRVz75EmyvhGXx+zhcIsV/viCGGKZTXPYv8UfR7a37mx0Qqyo3ZWZklnDSxnCOtW2Fr2AAW75+g0TSXPlGkPFqz4/ODNy9YIa/Au9A2QSKVaPdI0+7J8PHjEPBgsd1hyuuiYxovnv4JXrUEG1hlN47eyNnwdNPZ1qEfHFljqcaFmIWI+1g3MvalnoQjsTCAEXoAErw7RPu7S07Igu3x8Lza42cbPGg==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: general-strapi-database-secret
      namespace: standalone

