apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: general-strapi-minio-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgDJrJJwlOKt9maI5mtc92jxdXOYn1DuS8cE7lng7aqmdYgEKHSoY0SgVt0KOo6MkMBtqUEgBweBNHuMBOATQrV8G6e/NIxUHu7Uyg/YpdWsuBgdJikD5a0ipKusXKTDQzoFvxwCly0E/z3dboUoSnlJsyTIex3MZEfcARHSw5sLMDhQAoRBTIKM+hXqJUgn5QUWqq1IkXnz3CQqAXdPo026NknMjUtU0ees20WsTPpFnQpC/umw/0boCJuXL3vskC4epbxNO6KYYjR4sSFhv34aJ7O7B0f/BACOB7UQjSJ1yp/nEkAY936QLIaq1Zxl4D/jwSRkbbCrL1D/W0857LZgQVnlY2BhEmkjBI2HRvkuKFL+JtdZGy11S21EquyBcwWxrMzUjH5TeXByX5ewiphnIt4RDSo6kdgkobN8pJubpWwwfDgu1DyMbgGF1xIC2qjAn5zZdj9oEHKPUBjoxdl48aW1icVGxWdYnmehLo29PA2O7+s6buFa9IsnqJqRAF0k3QCWqO1ocw76tUI47aEUuh8oJBcqnHNGqgv8S5+M2Bc1EcGkWOAOkhMTq7y3gYoBOAjwm1N2bD7tJjxTxFqGeKZhn3IFAKf5duOboisuZ2y3s986GuiQ1upFDXUUERy7XJm4Q/eF6Cp8sYAHwveWULwlEsnKbwUrkaYjAuipuUKVRsv6bkxsh3B3AVhIoAeacNWes2SAytOOjbMsow==
    MINIO_SECRET_KEY: AgBqOxtr7HelMI704Yhvdsp815TMg1KnyIyzXoUv6NnYCUFQU9pcLdhgTPwtYUjrWev5S1WWC1prTgdInMtjFZPCa6emZCoF7B1ZPJAmIRX+/ryus0DkNq60QVnaX9QhJcxGZ7wtOZyRntO8LJlZ1UdQNyodCNvr7kzH8gIg2rxw7/5JC/23RcB0Nux92W7zAvZg7MHoQgQ5W2SJ/AhpV9pbddwe+sELL4tFpOn0j8yFi8tWQaTccGw+wCq45uW2fa4ttmZuLrOVMAOIJxYrMfeBd0WEUEra68tYfAy04JhTwa3StflRIDKeXKH/hustIPZLIO9Nefw+clRF0jXSkJInN2ymCYoTlxLqi5/EC+FU/f1deeGQuhvIdANUlTxPHFRqPTwO1bAp3rfqcQVqry/xp8XmlngPFwseJ9Q/6fjORf+Pqq9IyJZjroCo1cbqJWNAyPyqMRs+Znh1O6muXKuTdA++F2QqDkrHokSPxSLyUkVzuW1L/37kHyN280uAhjHDbedHUFzRNOn1z3a4AeKZiyKLHCM0HlLOZlvMrbnRJ46fRBM1WbR/Tbfz8S+BZwBYQFzFaBMT2l5PX4uqBBSnse0V4h+QVPXMrJzBoiFis4+xceBuEZj6sAiYlyqxJ/ZN+3+CQmXTy8np+53vy8kw6gBlCBiXqu8eotNCjZPW/aB1ELRJ3EzkLJ9+jRyY4pwaymmADNurggu6Xf7PwrnaQDk42eDos4M3MjXCGMVKDTUIF8TQrQvmWFmbWtdGH75fylti9fBdTQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: general-strapi-minio-secret
      namespace: ${NAMESPACE}
