apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: general-strapi-minio-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgADyD5J/UwqkP71BrV8AGDRKLCHqCOhUL7prYPuxYgqiNqF8Z2pHz5/jWJlqZKhiIxobijT9npRQa5sohnNsKpneADbOgpaxakdyq/ZqJwx18pDtf7rQeGmD8nyc7cZqNe5e/qQNfnTdXp4Lc8NZtRNcl/Zqauw/aAVequcXCXdIvOgIQshfxFMqGni//hiL/nrrpMPG5h1pLtvau4KfmRV2r1KAXu/tlpsT82ug3oVYTdDsW/uwgdIkbEmeUHNoJ7AftDKvaL/VKTi9cPEkFCSzss/4pgITzyS9ulsesxU1a+COej3JFuObwBiFoEBzPFiogKzEVw75YDuKokU9Fk0OG0ugB/QtaOjn3nTQZ6RdeHd8SBs7xgtMDU6Vmsb8atsRCy+JBsX5N1n86YB/t6/BLqri3eiNhEKzo05TjQevEv/kcwtZt1B85AeTuftKa21G1TkiJ1QZS0ENhZl3mJxsWdv+xLonZ9JXEjdy0AvTb0sCN1THcRM8VbFntlaqZbiLsmRYgxbQr5cx6bAHUiTiDFSrolmR7t84k8Lj4xSLbcmmhMN6mT+ogWN4t+OfYApaPeTiUQOuE5GDLtTD/lL+atzlSYqE1hyuc8iyzO3DNTNQkebFGMru5Kk7lFs6Rn0k+pZZRJ3ZhHFr82Htm03UU0NFoN3CSeEj+DeOVAznaPfIt21twjmdftgkZnZrHc7+Tpr6Uc0D7jFSjbQ5g==
    MINIO_SECRET_KEY: AgCYOmbA9ddYiVnyapsbEz+/XpeLSxQJSmjENLdJ+q3X0D83dIxdxWisepUoOPLg41ArOTMVDjKA/rrfuIXxHbLgUxWnkS587extdFfwrSxzaCdtTvoCjPn8a46D1QCE5rqm860KP3FUovYaBd01B4sDUz7HVXqlxhwj30wLLCs4e/m4aGgOWbcQSLw2IKthInzsRWqk5Ass/+oq8J2alWv45sul50qle7pcgVyLVZghGp9Aszf2h6ymT+PtMS81sBooNACPh3lOcC3bvYfdG059WDDY4pdA0E8DX3yEBHS6NNLkUKXiQ8A4pOvZO/k7rw4wkyw9TxFE12s3ti+Gnh/+IcANyG0WtDXv0x4sdO7we1Jo3Rzs8wn89LaruG4qFDxa73sVGYHVcAeB5cwtnAV6Rv46NerVnVZDq6hiILSzJ1P5YG3GTnLMnGCXA/EqmWwbPCm/V1oekTeEH6FO6nGxN0WzbuuYJhOOWB+SLWYYdVLTIoXxK93Mf23/C19rc94R3H3BA4qgMwQ23x7jDUeO7aGlnhmXRIck9r/Z623oNrQ9rJkjqD+bJuloZdTroW3b3L5qy3Wvdvq1Rm1vkZe2TJlWf0/S8iOVPzQRlFY1LsWQRsNSRk4uoT6JwuJdFau+kNwp0Rasdy7av2abNSfToLbt6oFjVNotL+q05JVY1hj5B4Q8PlE/fKEFX5at+TMKfoBWkuHyfZu81lHuURSGMqtSrugWfiu7Gt6RPmD/2zFxxLoftmUEjJimW4aDSzeeUQ7f7oYRtw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: general-strapi-minio-secret
      namespace: ${NAMESPACE}
