apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: general-strapi-minio-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgCSYvIcDo6TgEsIjueuiTOPALXuQsfEknXF+3uR6nqbuOHzcm3hAntdYCJ380VHL41JLZ0CzB3Cp45V2wRjxooTyX4qr8tPS+Im259a1crBeOzZy77DAKurnKDVzxt0/oNVEJVpwqypU5gN6l/KJwpLkR/e7IZCoroJJP/wbzgb0pEIUrb5glHXs7/TGRf3vDauu1N2y3rzbKzlqU//ID/jDbmeP79wzYslN2u5+k37UmrIpxm25p9yl54vMB4iAb31P4faSK5gjR6CTkyyBxnDWeMhbTQvPq3z6EdlljWrYT77sRJb+jgyaRMZE1ggdJ+A4inkwL4DrsvyL9l0kRhZ0ifXBMchxGcLWqyJ98aDp2B7S6RL5a4SraFtXhN+clIAbC5v6Yjbh1yaZhcgDzpL3g+OTCbwDaGnqZLktLz0JUo0d1J+H9aHLSEsvzmAlkdhDqraM6yVkGVAPtBJYKRd21zZjJZJ2g2bW3V0NtSuxTKY8B3H2SdzWo+3f7UoCvekpR3IdYxeW5rHJtVZm8dKIavsPmJOIkL7o/nPZmNu03s2WmGfCAj91FeD4E4VYeeB6OJ2aKE1eUiayJVFjXsKqKI2BNMvpUmwFKFBiL/DKjhJ16yBX8uhNBoUt71xejWBTiZsKhapEk/9ZtzJxT1aFNbuVtUsmdoJDidsxeBD8fsy2ohucVQzSPdvNs+S03cLeIPss7yhtwjF+Dr1uQ==
    MINIO_SECRET_KEY: AgAjyBCajYbso3jGImRbifpyp02WpMa9vm2HU5ZdHF0Yh/v6v0NpQkbQ3jjOnWF+T6UsTTA3R5vEs1mwbCYbrYthP5o9m4HiRv+4/GAwpBGItchngP4jYCCw/7vDlLPSBJBTWCrkvqSkvo29leYKfYtCHMITyn6DxUGMxivUg+DnBLlQJUJ1Mlqom9VWxa9TRx0bLE7CNmXdgkVaqdPnFw7qsuCcLVcKz79nvGFrIJjnPUaqEKi/Z6Iy8OuLErvDKaWQ/hyPIQmaLU//jk0ouIkWQRwXvFfINe6NVBp8KkzW2aN6E9m7IUHC866Ze0EWInMohuqV4gm4wO3ZlIHEy7LJ0GtFPFrI7r/7h/PWFX6G7j6+QocHPcmoNs4vdTty2K0bVBjPOib9X93Cmq1wOirWFdg6zfReNQ4RFpoYAEKOnv+JXCcOF7vVV4Y8C64nwx9KB+/RKY3EVONaiKOylXEk624ExP4D9XonKDlEMCMF2ykjna+1XaBdvrb+GTZOPpUeZ2YAlnozs3m17BcsSPobgz9ebIVjOGRyMOf0ShNTn95Z5fcT7ryJdwl1nehMMhJp2eTfuofgZkq4aI+Y7R3JcamGD6khLXgttJNJfZSV3FJnjt3uBwmNdFYlD6+9SDnyGHpeigD+29r90YrBp162IalCi/GQfiXTXQG1FXXig8SFtxHjRvOcxAA5Xt6qXALY/0p7hkC4Rxdxxo4Jxac08TsAYgpnWzDeErPKTRRZjJK/caG5ucP5RRALFboaHZlxUZTNUaFRlg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: general-strapi-minio-secret
      namespace: ${NAMESPACE}
