name: Build with bratiska-cli
on:
  pull_request:
    branches:
      - master
jobs:
  conditions:
    name: Check for build conditions
    uses: bratislava/github-actions/.github/workflows/build-conditions.yml@stable
    permissions: write-all

  strapi:
    name: build Strapi
    needs: conditions
    if: needs.conditions.outputs.strapi == 'true'
    uses: bratislava/github-actions/.github/workflows/build-with-bratiska-cli.yml@stable
    with:
      directory: /
      debug: --debug
    secrets:
      sentry-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
    permissions: write-all